# Generated by Django 5.2.13 on 2026-04-15 02:17

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('total_orders', models.IntegerField(default=0)),
                ('completed_orders', models.IntegerField(default=0)),
                ('cancelled_orders', models.IntegerField(default=0)),
                ('total_planned_quantity', models.IntegerField(default=0)),
                ('total_produced_quantity', models.IntegerField(default=0)),
                ('total_defective_quantity', models.IntegerField(default=0)),
                ('total_production_time', models.IntegerField(default=0, help_text='Total production time in seconds')),
                ('total_downtime', models.IntegerField(default=0, help_text='Total downtime in seconds')),
                ('average_oee', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('quality_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('total_alerts', models.IntegerField(default=0)),
                ('critical_alerts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Summary',
                'verbose_name_plural': 'Daily Summaries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='KPIRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kpi_type', models.CharField(choices=[('oee', 'OEE'), ('mtbf', 'MTBF (Mean Time Between Failures)'), ('mttr', 'MTTR (Mean Time To Repair)'), ('availability', 'Availability'), ('performance', 'Performance'), ('quality', 'Quality'), ('throughput', 'Throughput'), ('defect_rate', 'Defect Rate'), ('scrap_rate', 'Scrap Rate'), ('fpy', 'First Pass Yield'), ('takt_time', 'Takt Time')], db_index=True, max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('period_type', models.CharField(choices=[('shift', 'Shift'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'KPI Record',
                'verbose_name_plural': 'KPI Records',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective'), ('predictive', 'Predictive'), ('emergency', 'Emergency')], max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0, help_text='Total maintenance duration')),
                ('description', models.TextField()),
                ('work_performed', models.TextField(blank=True)),
                ('parts_replaced', models.JSONField(blank=True, default=list)),
                ('technician_name', models.CharField(blank=True, max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maintenance Record',
                'verbose_name_plural': 'Maintenance Records',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='OEERecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('availability', models.FloatField(help_text='Availability factor (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('performance', models.FloatField(help_text='Performance factor (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('quality', models.FloatField(help_text='Quality factor (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('oee', models.FloatField(help_text='OEE = Availability × Performance × Quality (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('planned_production_time', models.IntegerField(help_text='Planned production time in seconds')),
                ('actual_production_time', models.IntegerField(help_text='Actual production time in seconds')),
                ('downtime', models.IntegerField(default=0, help_text='Total downtime in seconds')),
                ('ideal_cycle_time', models.FloatField(default=0.0, help_text='Ideal cycle time in seconds per unit')),
                ('actual_cycle_time', models.FloatField(default=0.0, help_text='Actual cycle time in seconds per unit')),
                ('total_count', models.IntegerField(default=0)),
                ('good_count', models.IntegerField(default=0)),
                ('defect_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OEE Record',
                'verbose_name_plural': 'OEE Records',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspection_type', models.CharField(choices=[('visual', 'Visual Inspection'), ('dimensional', 'Dimensional Check'), ('functional', 'Functional Test'), ('material', 'Material Test'), ('final', 'Final Inspection')], max_length=50)),
                ('inspection_time', models.DateTimeField(auto_now_add=True)),
                ('quantity_inspected', models.IntegerField(default=0)),
                ('quantity_defective', models.IntegerField(default=0)),
                ('quantity_reworked', models.IntegerField(default=0)),
                ('quantity_accepted', models.IntegerField(default=0)),
                ('defect_rate', models.FloatField(default=0.0, help_text='Defect rate as percentage', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('defect_types', models.JSONField(blank=True, default=dict, help_text="{'type_name': count, ...}")),
                ('inspector_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quality Record',
                'verbose_name_plural': 'Quality Records',
                'ordering': ['-inspection_time'],
            },
        ),
    ]
