# Generated by Django 5.2.13 on 2026-04-15 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('core', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='production_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='production.productionline'),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='kpirecord',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_records', to='production.machine'),
        ),
        migrations.AddField(
            model_name='kpirecord',
            name='production_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_records', to='production.productionline'),
        ),
        migrations.AddField(
            model_name='kpirecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_records', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='production.machine'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='oeerecord',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oee_records', to='production.machine'),
        ),
        migrations.AddField(
            model_name='oeerecord',
            name='production_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oee_records', to='production.productionline'),
        ),
        migrations.AddField(
            model_name='oeerecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oee_records', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='qualityrecord',
            name='production_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_records', to='production.productionline'),
        ),
        migrations.AddField(
            model_name='qualityrecord',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_records', to='production.productionorder'),
        ),
        migrations.AddField(
            model_name='qualityrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_records', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='dailysummary',
            index=models.Index(fields=['tenant', '-date'], name='analytics_d_tenant__2875b1_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysummary',
            index=models.Index(fields=['production_line', '-date'], name='analytics_d_product_c922f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailysummary',
            unique_together={('production_line', 'date')},
        ),
        migrations.AddIndex(
            model_name='kpirecord',
            index=models.Index(fields=['tenant', 'kpi_type', '-period_end'], name='analytics_k_tenant__cc395d_idx'),
        ),
        migrations.AddIndex(
            model_name='kpirecord',
            index=models.Index(fields=['-period_end'], name='analytics_k_period__bc8da7_idx'),
        ),
        migrations.AddIndex(
            model_name='oeerecord',
            index=models.Index(fields=['tenant', '-date'], name='analytics_o_tenant__c23ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='oeerecord',
            index=models.Index(fields=['production_line', '-date'], name='analytics_o_product_435206_idx'),
        ),
        migrations.AddIndex(
            model_name='oeerecord',
            index=models.Index(fields=['machine', '-date'], name='analytics_o_machine_8957cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='oeerecord',
            unique_together={('machine', 'date')},
        ),
        migrations.AddIndex(
            model_name='qualityrecord',
            index=models.Index(fields=['production_order', '-inspection_time'], name='analytics_q_product_2892f1_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityrecord',
            index=models.Index(fields=['tenant', '-inspection_time'], name='analytics_q_tenant__76f311_idx'),
        ),
    ]
