# Generated by Django 5.2.13 on 2026-04-15 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fincas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlFitosanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_control', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=20)),
                ('plaga_enfermedad', models.CharField(choices=[('monilia', 'Monilia'), ('fitoftora', 'Fitóftora'), ('escoba_bruja', 'Escoba de bruja'), ('otra', 'Otra')], max_length=20)),
                ('tratamiento_aplicado', models.TextField()),
                ('resultado', models.CharField(blank=True, max_length=200)),
                ('foto_evidencia', models.URLField(blank=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='fincas.lote')),
            ],
            options={
                'verbose_name': 'Control fitosanitario',
                'verbose_name_plural': 'Controles fitosanitarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cosecha', models.DateField()),
                ('kg_baba', models.DecimalField(decimal_places=2, max_digits=8)),
                ('kg_seco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dias_fermentacion', models.PositiveSmallIntegerField()),
                ('temp_prom_fermentacion', models.DecimalField(decimal_places=1, max_digits=4)),
                ('dias_secado', models.PositiveSmallIntegerField()),
                ('calidad', models.CharField(choices=[('premium', 'Premium'), ('estandar', 'Estándar'), ('pasilla', 'Pasilla')], default='estandar', max_length=20)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosechas', to='fincas.lote')),
            ],
            options={
                'verbose_name': 'Cosecha',
                'verbose_name_plural': 'Cosechas',
                'ordering': ['-fecha_cosecha'],
            },
        ),
    ]
