# Generated by Django 5.2.13 on 2026-04-15 02:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_temp_min', models.FloatField(default=0.0)),
                ('default_temp_max', models.FloatField(default=250.0)),
                ('default_vibration_max', models.FloatField(default=10.0)),
                ('default_current_max', models.FloatField(default=30.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Machine Type',
                'verbose_name_plural': 'Machine Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('bom_reference', models.CharField(blank=True, max_length=200)),
                ('standard_cycle_time', models.FloatField(default=60.0, help_text='Standard cycle time in seconds')),
                ('quality_target', models.FloatField(default=0.95, help_text='Target quality as decimal (0.95 = 95%)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['sku'],
                'unique_together': {('tenant', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('shifts_per_day', models.IntegerField(default=1)),
                ('hours_per_shift', models.FloatField(default=8.0)),
                ('is_active', models.BooleanField(default=True)),
                ('target_oee', models.FloatField(default=0.85, help_text='Target OEE as decimal (0.85 = 85%)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_lines', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Production Line',
                'verbose_name_plural': 'Production Lines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('machine_type', models.CharField(choices=[('injection', 'Injection Molding'), ('cutting', 'Cutting'), ('stitching', 'Stitching'), ('assembly', 'Assembly'), ('finishing', 'Finishing'), ('packaging', 'Packaging'), ('other', 'Other')], max_length=50)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('warning', 'Warning'), ('maintenance', 'Maintenance'), ('idle', 'Idle')], default='offline', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('temp_min', models.FloatField(default=0.0)),
                ('temp_max', models.FloatField(default=250.0)),
                ('vibration_max', models.FloatField(default=10.0)),
                ('current_max', models.FloatField(default=30.0)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('last_maintenance_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='production.productionline')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], default=2)),
                ('quantity_planned', models.IntegerField(default=0)),
                ('quantity_completed', models.IntegerField(default=0)),
                ('quantity_defective', models.IntegerField(default=0)),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('planned_end', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='production.product')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='production.productionline')),
            ],
            options={
                'verbose_name': 'Production Order',
                'verbose_name_plural': 'Production Orders',
                'ordering': ['-priority', 'planned_start'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('produced_quantity', models.IntegerField(default=0)),
                ('defective_quantity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.productionorder')),
            ],
            options={
                'verbose_name': 'Production Order Item',
                'verbose_name_plural': 'Production Order Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('shift_type', models.CharField(choices=[('day', 'Day Shift'), ('afternoon', 'Afternoon Shift'), ('night', 'Night Shift'), ('custom', 'Custom')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days_of_week', models.JSONField(default=list, help_text='List of days [0,1,2,3,4] for Mon-Fri')),
                ('is_active', models.BooleanField(default=True)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='production.productionline')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'ordering': ['start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='productionline',
            index=models.Index(fields=['tenant', 'slug'], name='production__tenant__3b96e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productionline',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['production_line', 'slug'], name='production__product_d00eba_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['status'], name='production__status_1859bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='machine',
            unique_together={('production_line', 'slug')},
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['status', 'planned_start'], name='production__status_98cf4c_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['production_line', 'status'], name='production__product_e4dd94_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productionorderitem',
            unique_together={('order', 'batch_number')},
        ),
    ]
