# Generated by Django 5.2.13 on 2026-04-15 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fincas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('temp_suelo', 'Temperatura suelo'), ('hum_suelo', 'Humedad suelo'), ('temp_ferm', 'Temperatura fermentación'), ('hum_secado', 'Humedad secado'), ('ph_suelo', 'pH suelo')], db_index=True, max_length=20)),
                ('valor', models.FloatField()),
                ('unidad', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='fincas.lote')),
            ],
            options={
                'verbose_name': 'Lectura de sensor',
                'verbose_name_plural': 'Lecturas de sensores',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['lote', 'tipo', '-timestamp'], name='iot_sensord_lote_id_40379b_idx')],
            },
        ),
    ]
