# Generated by Django 5.2.13 on 2026-04-15 02:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature'), ('vibration', 'Vibration'), ('current', 'Current'), ('pressure', 'Pressure'), ('humidity', 'Humidity'), ('rpm', 'RPM'), ('counter', 'Counter'), ('custom', 'Custom')], max_length=50)),
                ('unit', models.CharField(choices=[('°C', 'Celsius'), ('°F', 'Fahrenheit'), ('mm/s', 'Vibration mm/s'), ('A', 'Amperes'), ('V', 'Volts'), ('Pa', 'Pascals'), ('%', 'Percentage'), ('rpm', 'RPM'), ('counts', 'Counts')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sampling_rate', models.IntegerField(default=1, help_text='Sampling rate in seconds')),
                ('threshold_min', models.FloatField(blank=True, null=True)),
                ('threshold_max', models.FloatField(blank=True, null=True)),
                ('threshold_critical_min', models.FloatField(blank=True, null=True)),
                ('threshold_critical_max', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='production.machine')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
                'ordering': ['machine', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('metric', models.CharField(choices=[('temperature', 'Temperature'), ('vibration', 'Vibration'), ('current', 'Current'), ('defect_rate', 'Defect Rate')], max_length=50)),
                ('operator', models.CharField(choices=[('gt', 'Greater Than'), ('lt', 'Less Than'), ('eq', 'Equal To'), ('gte', 'Greater Than or Equal'), ('lte', 'Less Than or Equal')], max_length=10)),
                ('threshold', models.FloatField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('cooldown_seconds', models.IntegerField(default=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensor', models.ForeignKey(blank=True, help_text='Leave empty to apply to all sensors of similar type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='telemetry.sensor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('operational_status', models.CharField(choices=[('running', 'Running'), ('idle', 'Idle'), ('stopped', 'Stopped'), ('maintenance', 'Maintenance'), ('fault', 'Fault')], default='running', max_length=20)),
                ('production_count', models.IntegerField(default=0)),
                ('defects', models.IntegerField(default=0)),
                ('temperature', models.FloatField(help_text='Temperature in Celsius', validators=[django.core.validators.MinValueValidator(-50.0), django.core.validators.MaxValueValidator(500.0)])),
                ('vibration', models.FloatField(help_text='Vibration in mm/s', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('current', models.FloatField(help_text='Current in Amperes', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('uptime', models.IntegerField(default=0)),
                ('mqtt_topic', models.CharField(blank=True, max_length=500)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_events', to='production.machine')),
            ],
            options={
                'verbose_name': 'Telemetry Event',
                'verbose_name_plural': 'Telemetry Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('metric_value', models.FloatField()),
                ('threshold_value', models.FloatField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_telemetry_alerts', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='telemetry.alertrule')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='telemetry.sensor')),
                ('telemetry_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='telemetry.telemetryevent')),
            ],
            options={
                'verbose_name': 'Telemetry Alert',
                'verbose_name_plural': 'Telemetry Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='telemetryevent',
            index=models.Index(fields=['machine', '-timestamp'], name='telemetry_t_machine_00b84d_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryevent',
            index=models.Index(fields=['-timestamp'], name='telemetry_t_timesta_933293_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryalert',
            index=models.Index(fields=['sensor', '-created_at'], name='telemetry_t_sensor__e269e1_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryalert',
            index=models.Index(fields=['status', '-created_at'], name='telemetry_t_status_520a92_idx'),
        ),
    ]
