# Generated by Django 5.2.13 on 2026-04-15 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('municipio', models.CharField(max_length=80)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('area_total_ha', models.DecimalField(decimal_places=2, max_digits=6)),
                ('verificada', models.BooleanField(default=False)),
                ('foto', models.URLField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('telefono_wa', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fincas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finca',
                'verbose_name_plural': 'Fincas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('variedad', models.CharField(choices=[('criollo', 'Criollo'), ('trinitario', 'Trinitario'), ('forastero', 'Forastero'), ('ccn51', 'CCN-51'), ('ics60', 'ICS-60'), ('ics95', 'ICS-95'), ('acriollado', 'Criollo acriollado'), ('otro', 'Otro')], max_length=20)),
                ('num_plantas', models.PositiveIntegerField()),
                ('edad_años', models.PositiveSmallIntegerField()),
                ('area_ha', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('renovacion', 'En renovación'), ('improductivo', 'Improductivo')], default='activo', max_length=20)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='fincas.finca')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
        migrations.CreateModel(
            name='PerfilExportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificaciones', models.JSONField(blank=True, default=list)),
                ('mercados_destino', models.JSONField(blank=True, default=list)),
                ('capacidad_anual_kg', models.PositiveIntegerField(default=0)),
                ('qr_url', models.URLField(blank=True)),
                ('finca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_exportacion', to='fincas.finca')),
            ],
            options={
                'verbose_name': 'Perfil de exportación',
                'verbose_name_plural': 'Perfiles de exportación',
            },
        ),
    ]
